version: 0.2
env:
    git-credential-helper: yes 
phases:  
  build:
    commands: 
    - echo "CODEBUILD_RESOLVED_SOURCE_VERSION => $CODEBUILD_RESOLVED_SOURCE_VERSION"
    - echo "CODEBUILD_WEBHOOK_HEAD_REF => $CODEBUILD_WEBHOOK_HEAD_REF"
      git  version
      file1=`git show --pretty="format:" --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION`
    - echo "$file"
      for val in $file
      if [ "val" == "compaction/*" ]
      then
      aws s3 cp $file s3://codepipeline-artifacts-bucket1/Compaction_Glue_Pipe/*
      aws codepipeline start-pipeline-execution --name Compaction_Glue_Pipepine
      else
    - echo "Popat"
      fi
   
      
