version: 0.2
env:
    git-credential-helper: yes 
phases:  
  build:
    commands: 
    - echo "CODEBUILD_RESOLVED_SOURCE_VERSION => $CODEBUILD_RESOLVED_SOURCE_VERSION"
    - echo "CODEBUILD_WEBHOOK_HEAD_REF => $CODEBUILD_WEBHOOK_HEAD_REF"
      git  version
      file=`git show --pretty="format:" --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION`
    - echo "$file"
      while [ $file =="compaction/*" ]    # this is loop1
      do
      aws s3 cp $file s3://lambdagluepipedemo/*
      aws codepipeline start-pipeline-execution --name Compaction_Glue_dem
      while [ $file == "Ingestion/*" ]  # this is loop2
      do
      aws s3 cp $file s3://lambdagluepipedemo/*
      aws codepipeline start-pipeline-execution --name lambda-pipeline
      done
    - echo "Pot"
      done
   
      
