version: 0.2
env:
    git-credential-helper: yes 
phases:  
  build:
    commands: | 
        echo "CODEBUILD_RESOLVED_SOURCE_VERSION => $CODEBUILD_RESOLVED_SOURCE_VERSION"
        echo "CODEBUILD_WEBHOOK_HEAD_REF => $CODEBUILD_WEBHOOK_HEAD_REF"
        git version
        file=`git show --pretty="format:" --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION`
        echo "$file"
        zip -r compaction.zip $file
        echo "compress compaction folder"
        if [ "$file" == "compaction/*" ]
        then
        aws s3 cp compaction.zip s3://codepipeline-artifacts-bucket1
        aws codepipeline start-pipeline-execution --name code-pipelinepoc
        else
        echo "democid" 
        fi
